// Copyright 2026 dskibickikono-lang. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL       string            `toml:"base_url"`
	AuthHeaderVal string            `toml:"auth_header"`
	Headers       map[string]string `toml:"headers,omitempty"`
	Bizraport     BizraportConfig   `toml:"bizraport"`
	AuthSource    string            `toml:"-"`
	Path          string            `toml:"-"`
}

// BizraportConfig holds credentials and tuning for the bizraport.pl
// registry API used by the `enrich` command. Credentials may also be
// supplied via BIZRAPORT_EMAIL / BIZRAPORT_PASSWORD env vars, which
// override the file values.
type BizraportConfig struct {
	Email    string  `toml:"email"`
	Password string  `toml:"password"`
	BaseURL  string  `toml:"base_url,omitempty"`
	RPS      float64 `toml:"rps,omitempty"`
}

// Configured reports whether both bizraport credentials are present.
func (b BizraportConfig) Configured() bool {
	return b.Email != "" && b.Password != ""
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://www.olx.pl",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("OLX_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "olx-pp-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "") {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("OLX_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}

	// bizraport.pl credentials: env vars override the config file so secrets
	// can stay out of the file when desired.
	if v := os.Getenv("BIZRAPORT_EMAIL"); v != "" {
		cfg.Bizraport.Email = v
	}
	if v := os.Getenv("BIZRAPORT_PASSWORD"); v != "" {
		cfg.Bizraport.Password = v
	}
	if v := os.Getenv("BIZRAPORT_BASE_URL"); v != "" {
		cfg.Bizraport.BaseURL = v
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

// Ensure strings import is used
var _ = strings.ReplaceAll
