// Copyright 2026 dskibickikono-lang. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/mark3labs/mcp-go/server"
	mcptools "github.com/dskibickikono-lang/olx-pp-cli/internal/mcp"
)

func main() {
	s := server.NewMCPServer(
		"Olx",
		"1.0.0",
		server.WithToolCapabilities(false),
	)

	readOnly := false
	for _, arg := range os.Args[1:] {
		if arg == "--read-only" {
			readOnly = true
		}
	}
	if strings.ToLower(os.Getenv("READ_ONLY_MODE")) == "true" {
		readOnly = true
	}

	mcptools.RegisterTools(s, readOnly)

	if err := server.ServeStdio(s); err != nil {
		fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
		os.Exit(1)
	}
}
